use_frameworks!

platform :ios, '8.0'

target 'RSVideoLibs_Example' do
  pod 'RSVideoLibs', :path => '../'

  target 'RSVideoLibs_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
